Add "About" section to README
ardaku/arc pull request #16
Opened 2022-04-29 04:46 UTC by AldaronLau

I based this text off of what I sent in the Discord.  Any typos / grammar / content things I should change?

2022-04-29 04:49 UTC, hyperswine approved these changes
Good start

2022-04-29 10:16 UTC, DesmondWillowbrook requested changes

2022-04-29 10:16 UTC, kartva commented on README.md
> +[custom data section](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#name-section%E2%91%A0)
```suggestion
[custom data section](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#binary-customsec)
```

The previous link referred to the `name` custom section, which has been assigned by the spec to contain debug information.

We'll be storing storing app metadata in a custom section with a name _other_ than `name`. (For example, store all data under the name `quantii` or something else, then have submodules to store multiple pieces of metadata, similar to how the `name` custom section contains debug information for multiple functions)

2022-04-29 10:16 UTC, kartva commented on README.md
> +is a message channel for interacting with hardware.
[WASI already has a lot of permission stuff built in revolving around UNIX-style file descriptors](https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-overview.md#capability-oriented) which sounds _similar_, but the channels concepts seem to be a Daku thing instead of an OS thing.

2022-04-30 03:40 UTC, AldaronLau commented on README.md
> +[custom data section](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#name-section%E2%91%A0)
Good catch!

2022-04-30 03:52 UTC, AldaronLau commented on README.md
> +is a message channel for interacting with hardware.
Interesting, slightly different design philosophies between the two:

WASI: As long as there is an owned file descriptor, you have access to child resources.
Daku: As long as there is a permission, the you can have access to owned root level resources in the app sandbox.

2022-04-30 03:53 UTC, merged