More info (for real this time)
ardaku/arc pull request #22
Opened 2022-06-17 13:08 UTC by CATboardBETA

2022-06-17 13:18 UTC, hyperswine reviewed
works for me, but doesnt pass tests

2022-06-17 13:26 UTC, hyperswine approved these changes
Looks good

2022-06-17 17:37 UTC, AldaronLau requested changes
What's the initfs/home/.qiishenv file for?

2022-06-17 17:37 UTC, AldaronLau commented on quantii/src/lib.rs
>  extern crate compiler_builtins_patch;
The comment should apply to the line below.  Basically, `extern crate alloc` should be moved one line up.

2022-06-17 17:37 UTC, AldaronLau commented on quantii/src/lib.rs
> +    }
There's no need to use allocation here.  Since all of the messages are static `&str` types.

2022-06-17 17:37 UTC, AldaronLau commented on quantii/src/lib.rs
> +                msg = "Ardaku: Error: Invalid WASM file".to_owned()
Should combine let and match into one expression.

```suggestion
    let msg = match ardaku::start(System, APP_EXE) {
        Ok(_) => "\n=== ARDAKU SUCCESSFULLY EXECUTED ===\n",
        Err(e) => match e {
            ArdakuError::InvalidWasm => {
                "Ardaku: Error: Invalid WASM file"
```

2022-06-20 23:48 UTC, AldaronLau requested changes

2022-06-20 23:48 UTC, AldaronLau commented on config/linux.toml
> +#build-std-features = ["compiler-builtins-mem"]
We'll want to undo all changes to this file.

2022-06-20 23:58 UTC, AldaronLau approved these changes

2022-06-21 00:04 UTC, merged